"""create job_applications table

Revision ID: 2677b6836cb3
Revises: 3ca5e59e688a
Create Date: 2026-05-13 09:50:30.214096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2677b6836cb3'
down_revision: Union[str, Sequence[str], None] = '3ca5e59e688a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('student_membership_id', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('pan_number', sa.String(), nullable=True),
    sa.Column('pan_card_file', sa.String(), nullable=True),
    sa.Column('resume_file', sa.String(), nullable=True),
    sa.Column('photo_file', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('highest_qualification', sa.String(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('university', sa.String(), nullable=True),
    sa.Column('college', sa.String(), nullable=True),
    sa.Column('year_of_passing', sa.String(), nullable=True),
    sa.Column('position_applied_for', sa.String(), nullable=True),
    sa.Column('preferred_work_mode', sa.String(), nullable=True),
    sa.Column('key_skills', sa.Text(), nullable=True),
    sa.Column('expected_salary', sa.String(), nullable=True),
    sa.Column('why_hire_me', sa.Text(), nullable=True),
    sa.Column('experience_type', sa.String(), nullable=True),
    sa.Column('experiences', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_applications_id'), 'job_applications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_applications_id'), table_name='job_applications')
    op.drop_table('job_applications')
    # ### end Alembic commands ###
