"""update job fair fields

Revision ID: 34ec925364a4
Revises: 37f12d910b4b
Create Date: 2026-06-08 15:18:28.513510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34ec925364a4'
down_revision: Union[str, Sequence[str], None] = '37f12d910b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # FK recreation (optional)
    op.drop_constraint(
        op.f('event_job_roles_job_fair_id_fkey'),
        'event_job_roles',
        type_='foreignkey'
    )

    op.create_foreign_key(
        None,
        'event_job_roles',
        'job_fairs',
        ['job_fair_id'],
        ['id']
    )

    # New fields
    op.add_column(
        'job_fairs',
        sa.Column(
            'organization_name',
            sa.String(length=255),
            nullable=True
        )
    )

    op.add_column(
        'job_fairs',
        sa.Column(
            'contact_number',
            sa.String(length=20),
            nullable=True
        )
    )

    op.add_column(
        'job_fairs',
        sa.Column(
            'contact_email',
            sa.String(length=255),
            nullable=True
        )
    )

    op.add_column(
        'job_fairs',
        sa.Column(
            'banner_image',
            sa.String(length=500),
            nullable=True
        )
    )

    op.add_column(
        'job_fairs',
        sa.Column(
            'start_time',
            sa.String(length=20),
            nullable=True
        )
    )

    op.add_column(
        'job_fairs',
        sa.Column(
            'end_time',
            sa.String(length=20),
            nullable=True
        )
    )

    op.add_column(
        'job_fairs',
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=True
        )
    )

    op.add_column(
        'job_fairs',
        sa.Column(
            'updated_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=True
        )
    )

    # Existing fields mandatory
    op.alter_column(
        'job_fairs',
        'service_id',
        existing_type=sa.Integer(),
        nullable=False
    )

    op.alter_column(
        'job_fairs',
        'title',
        existing_type=sa.String(),
        nullable=False
    )

    op.alter_column(
        'job_fairs',
        'description',
        existing_type=sa.String(),
        nullable=False
    )

    op.alter_column(
        'job_fairs',
        'start_date',
        existing_type=sa.Date(),
        nullable=False
    )

    op.alter_column(
        'job_fairs',
        'end_date',
        existing_type=sa.Date(),
        nullable=False
    )

    op.alter_column(
        'job_fairs',
        'location',
        existing_type=sa.String(),
        nullable=False
    )

    # Remove old fields
    op.drop_column('job_fairs', 'organizer_name')
    op.drop_column('job_fairs', 'event_mode')
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_fairs', sa.Column('event_mode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('job_fairs', sa.Column('organizer_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('job_fairs', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('job_fairs', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('job_fairs', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('job_fairs', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('job_fairs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('job_fairs', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('job_fairs', 'updated_at')
    op.drop_column('job_fairs', 'created_at')
    op.drop_column('job_fairs', 'end_time')
    op.drop_column('job_fairs', 'start_time')
    op.drop_column('job_fairs', 'banner_image')
    op.drop_column('job_fairs', 'contact_email')
    op.drop_column('job_fairs', 'contact_number')
    op.drop_column('job_fairs', 'organization_name')
    op.drop_constraint(None, 'event_job_roles', type_='foreignkey')
    op.create_foreign_key(op.f('event_job_roles_job_fair_id_fkey'), 'event_job_roles', 'job_fairs', ['job_fair_id'], ['id'], ondelete='CASCADE')
    