"""add job_fair_id

Revision ID: 3794bb5466ed
Revises: a98b7941e614
Create Date: 2026-05-30 15:16:37.942432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3794bb5466ed'
down_revision: Union[str, Sequence[str], None] = 'a98b7941e614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_registrations', sa.Column('job_fair_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event_registrations', 'job_fairs', ['job_fair_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_registrations', type_='foreignkey')
    op.drop_column('event_registrations', 'job_fair_id')
    # ### end Alembic commands ###
