"""update registration fields

Revision ID: 449ddf289d80
Revises: 3794bb5466ed
Create Date: 2026-06-01 11:58:00.994406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '449ddf289d80'
down_revision: Union[str, Sequence[str], None] = '3794bb5466ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_registrations', sa.Column('iam_a', sa.String(), nullable=True))
    op.add_column('event_registrations', sa.Column('receive_updates', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_event_registrations_id'), table_name='event_registrations')
    op.drop_column('event_registrations', 'company_url')
    op.drop_column('event_registrations', 'forwarded_to')
    op.drop_column('event_registrations', 'approved_at')
    op.drop_column('event_registrations', 'resume')
    op.drop_column('event_registrations', 'approved_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_registrations', sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('event_registrations', sa.Column('resume', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event_registrations', sa.Column('approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('event_registrations', sa.Column('forwarded_to', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event_registrations', sa.Column('company_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_event_registrations_id'), 'event_registrations', ['id'], unique=False)
    op.drop_column('event_registrations', 'receive_updates')
    op.drop_column('event_registrations', 'iam_a')
    # ### end Alembic commands ###
