"""add created by fields to black profiles

Revision ID: 55bbc08bc0b6
Revises: 72f059dd2c4f
Create Date: 2026-06-06 11:57:34.358563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55bbc08bc0b6'
down_revision: Union[str, Sequence[str], None] = '72f059dd2c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('black_profiles', sa.Column('employee_name', sa.String(length=255), nullable=True))
    op.add_column('black_profiles', sa.Column('photo_url', sa.String(length=500), nullable=True))
    op.add_column('black_profiles', sa.Column('uid_number', sa.String(length=100), nullable=True))
    op.add_column('black_profiles', sa.Column('employee_id', sa.String(length=100), nullable=True))
    op.add_column('black_profiles', sa.Column('aadhaar_number', sa.String(length=50), nullable=True))
    op.add_column('black_profiles', sa.Column('pan_number', sa.String(length=50), nullable=True))
    op.add_column('black_profiles', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('black_profiles', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('black_profiles', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('black_profiles', sa.Column('department', sa.String(length=255), nullable=True))
    op.add_column('black_profiles', sa.Column('mode_of_work', sa.String(length=100), nullable=True))
    op.add_column('black_profiles', sa.Column('reporting_to', sa.String(length=255), nullable=True))
    op.add_column('black_profiles', sa.Column('date_of_joining', sa.DateTime(), nullable=True))
    op.add_column('black_profiles', sa.Column('experience', sa.String(length=100), nullable=True))
    op.add_column('black_profiles', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('black_profiles', sa.Column('document_name', sa.String(length=255), nullable=True))
    op.add_column('black_profiles', sa.Column('document_url', sa.String(length=500), nullable=True))
    op.add_column('black_profiles', sa.Column('hr_name', sa.String(length=255), nullable=True))
    op.add_column('black_profiles', sa.Column('organisation', sa.String(length=255), nullable=True))
    op.add_column('black_profiles', sa.Column('hr_department', sa.String(length=255), nullable=True))
    op.add_column('black_profiles', sa.Column('created_by', sa.String(length=50), nullable=True))
    op.add_column('black_profiles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('black_profiles', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_black_profiles_id'), table_name='black_profiles')
    op.drop_column('black_profiles', 'reason')
    op.drop_column('black_profiles', 'name')
    op.drop_column('black_profiles', 'company')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('black_profiles', sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('black_profiles', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('black_profiles', sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_black_profiles_id'), 'black_profiles', ['id'], unique=False)
    op.drop_column('black_profiles', 'created_by_id')
    op.drop_column('black_profiles', 'created_at')
    op.drop_column('black_profiles', 'created_by')
    op.drop_column('black_profiles', 'hr_department')
    op.drop_column('black_profiles', 'organisation')
    op.drop_column('black_profiles', 'hr_name')
    op.drop_column('black_profiles', 'document_url')
    op.drop_column('black_profiles', 'document_name')
    op.drop_column('black_profiles', 'remarks')
    op.drop_column('black_profiles', 'experience')
    op.drop_column('black_profiles', 'date_of_joining')
    op.drop_column('black_profiles', 'reporting_to')
    op.drop_column('black_profiles', 'mode_of_work')
    op.drop_column('black_profiles', 'department')
    op.drop_column('black_profiles', 'location')
    op.drop_column('black_profiles', 'phone')
    op.drop_column('black_profiles', 'email')
    op.drop_column('black_profiles', 'pan_number')
    op.drop_column('black_profiles', 'aadhaar_number')
    op.drop_column('black_profiles', 'employee_id')
    op.drop_column('black_profiles', 'uid_number')
    op.drop_column('black_profiles', 'photo_url')
    op.drop_column('black_profiles', 'employee_name')
    # ### end Alembic commands ###
