"""create uploaded_files table

Revision ID: 585e8c446669
Revises: 3240a7392ab5
Create Date: 2026-05-13 10:28:06.396703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '585e8c446669'
down_revision: Union[str, Sequence[str], None] = '3240a7392ab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_files', sa.Column('file_name', sa.String(), nullable=False))
    op.alter_column('uploaded_files', 'membership_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('uploaded_files', 'file_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('uploaded_files', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('uploaded_files', 'stored_name')
    op.drop_column('uploaded_files', 'original_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_files', sa.Column('original_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('uploaded_files', sa.Column('stored_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('uploaded_files', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('uploaded_files', 'file_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('uploaded_files', 'membership_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('uploaded_files', 'file_name')
    # ### end Alembic commands ###
