"""update student password hash

Revision ID: 59ddf8d0ded6
Revises: 1c19132440d6
Create Date: 2026-05-26 14:56:49.172456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ddf8d0ded6'
down_revision: Union[str, Sequence[str], None] = '1c19132440d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_autonomous_details', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('student_university_details', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_university_details', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('student_autonomous_details', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
