"""create member benefits

Revision ID: 72f059dd2c4f
Revises: 4de640ddbdef
Create Date: 2026-06-06 10:51:12.977332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f059dd2c4f'
down_revision: Union[str, Sequence[str], None] = '4de640ddbdef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_benefits', sa.Column('category', sa.String(length=50), nullable=False))
    op.add_column('member_benefits', sa.Column('content', sa.String(length=1000), nullable=False))
    op.add_column('member_benefits', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('member_benefits', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('member_benefits', 'is_active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               postgresql_using='is_active::boolean',
               existing_nullable=True)
    op.drop_column('member_benefits', 'title')
    op.drop_column('member_benefits', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_benefits', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('member_benefits', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('member_benefits', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('member_benefits', 'updated_at')
    op.drop_column('member_benefits', 'created_at')
    op.drop_column('member_benefits', 'content')
    op.drop_column('member_benefits', 'category')
    # ### end Alembic commands ###
