"""sync models

Revision ID: 7be23ab21a89
Revises: a9b1bb3877be
Create Date: 2026-05-30 12:45:21.393028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7be23ab21a89'
down_revision: Union[str, Sequence[str], None] = 'a9b1bb3877be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_job_roles', sa.Column('job_fair_id', sa.Integer(), nullable=True))
    op.add_column('event_job_roles', sa.Column('company_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_event_job_roles_id'), 'event_job_roles', ['id'], unique=False)
    op.drop_constraint(op.f('event_job_roles_event_id_fkey'), 'event_job_roles', type_='foreignkey')
    op.create_foreign_key(None, 'event_job_roles', 'job_fairs', ['job_fair_id'], ['id'], ondelete='CASCADE')
    op.drop_column('event_job_roles', 'event_id')
    op.drop_constraint(op.f('event_registrations_member_id_fkey'), 'event_registrations', type_='foreignkey')
    op.drop_constraint(op.f('event_registrations_event_id_fkey'), 'event_registrations', type_='foreignkey')
    op.create_foreign_key(None, 'event_registrations', 'service_events', ['event_id'], ['id'])
    op.create_foreign_key(None, 'event_registrations', 'members', ['member_id'], ['id'])
    op.alter_column('job_fairs', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_job_fairs_id'), 'job_fairs', ['id'], unique=False)
    op.alter_column('service_events', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_events', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_job_fairs_id'), table_name='job_fairs')
    op.alter_column('job_fairs', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'event_registrations', type_='foreignkey')
    op.drop_constraint(None, 'event_registrations', type_='foreignkey')
    op.create_foreign_key(op.f('event_registrations_event_id_fkey'), 'event_registrations', 'service_events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('event_registrations_member_id_fkey'), 'event_registrations', 'members', ['member_id'], ['id'], ondelete='CASCADE')
    op.add_column('event_job_roles', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'event_job_roles', type_='foreignkey')
    op.create_foreign_key(op.f('event_job_roles_event_id_fkey'), 'event_job_roles', 'service_events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_event_job_roles_id'), table_name='event_job_roles')
    op.drop_column('event_job_roles', 'company_name')
    op.drop_column('event_job_roles', 'job_fair_id')
    # ### end Alembic commands ###
