"""Update user model

Revision ID: a1f6810d14b7
Revises: 7ec503bda661
Create Date: 2026-09-25 13:13:24.821411

This migration contains only the intended changes for the `users` table.
Unrelated autogenerated changes to other tables have been removed.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a1f6810d14b7"
down_revision: Union[str, Sequence[str], None] = "7ec503bda661"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Update users columns.
    op.alter_column(
        "users",
        "password",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )

    op.alter_column(
        "users",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )

    op.alter_column(
        "users",
        "is_approved",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )

    # Replace existing unique constraints with unique indexes,
    # matching the current User model metadata.
    op.drop_constraint(
        "users_email_key",
        "users",
        type_="unique",
    )

    op.drop_constraint(
        "users_membership_id_key",
        "users",
        type_="unique",
    )

    op.create_index(
        "ix_users_email",
        "users",
        ["email"],
        unique=True,
    )

    op.create_index(
        "ix_users_membership_id",
        "users",
        ["membership_id"],
        unique=True,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(
        "ix_users_membership_id",
        table_name="users",
    )

    op.drop_index(
        "ix_users_email",
        table_name="users",
    )

    op.create_unique_constraint(
        "users_membership_id_key",
        "users",
        ["membership_id"],
    )

    op.create_unique_constraint(
        "users_email_key",
        "users",
        ["email"],
    )

    op.alter_column(
        "users",
        "is_approved",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )

    op.alter_column(
        "users",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )

    op.alter_column(
        "users",
        "password",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
