"""add password hash to students

Revision ID: ed36fd43ec5d
Revises: 585e8c446669
Create Date: 2026-05-26 10:52:54.874232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed36fd43ec5d'
down_revision: Union[str, Sequence[str], None] = '585e8c446669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_autonomous_details', sa.Column('password_hash', sa.String(), nullable=False))
    op.add_column('student_university_details', sa.Column('password_hash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_university_details', 'password_hash')
    op.drop_column('student_autonomous_details', 'password_hash')
    # ### end Alembic commands ###
