"""create board members

Revision ID: ee8341589428
Revises: 9de7618de998
Create Date: 2026-06-05 10:28:09.364568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee8341589428'
down_revision: Union[str, Sequence[str], None] = '9de7618de998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('professional_title', sa.String(length=255), nullable=False),
    sa.Column('current_position', sa.String(length=255), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.Column('linkedin_url', sa.String(length=500), nullable=False),
    sa.Column('twitter_url', sa.String(length=500), nullable=False),
    sa.Column('facebook_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_members_id'), 'board_members', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_board_members_id'), table_name='board_members')
    op.drop_table('board_members')
    # ### end Alembic commands ###
